### ISSUE TITLE
SLIP encoded file

### ISSUE THREAD

**Issue by chazhenry** [rhjdjong/SlipLib#17]
I have log files that were collected raw and saved in SLIP format. Do you know of examples that show sliplib reading and decoding files? Thanks.

**Comment by rhjdjong** [comment]
The following should work:
```
from sliplib import SlipStream
with open(<yourfile>, mode='rb') as slip_file:   # Don't forget to use binary mode, otherwise you may get corrupt results
    slip_stream = SlipStream(slip_file)
    while True:
        msg = slip_stream.recv_msg()  # Get a decoded message
        if msg == b'':
            break
        # Do your analysis on the decoded message
```
I'll try to add examples for this in the documentation in the coming weeks.

**Comment by rhjdjong** [comment]
Added examples in the documentation. Also made SlipWrapper (and its derived classes) iterable, so the previous example can now be written as:

```
from sliplib import SlipStream
with open(<yourfile>, mode='rb') as slip_file:
    slip_stream = SlipStream(slip_file)
    for msg in slip_stream:
        # Do your analysis on the decoded message
```

I will close this issue.
