### ISSUE TITLE
Remove sphinx dependency 

### ISSUE THREAD

**Issue by samvasko** [rhjdjong/SlipLib#9]
Due to following line in setup.py
```
install_requires=['sphinx_rtd_theme']
```

Whole of sphinx and bunch of other packages are pulled in for installation. The sphinx certainly feels like a dev dependency.

**Comment by rhjdjong** [comment]
Thanks for reporting this. You are correct, this is not needed to just use the library.
I only work on this in my spare time, but I will try to fix this a.s.a.p.

**Comment by samvasko** [comment]
nice. thank you and great work on this package!
